WEB_SERVER_ADDRESS: 127.0.0.1:8001


LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
        console:
            format: "%(message)s"
            #format: "%(levelname)s %(name)s: %(message)s"
        simple:
            format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            #formatter: simple
            formatter: console
            stream: ext://sys.stdout
    nameko_openapi:
        level: DEBUG
        handlers: [console]
    root:
        level: INFO
        handlers: [console]

